server:
  port: 8082

logging:
  level:
    root: INFO
    ru.zentsova.deal: DEBUG
    org.springframework: INFO
    org.zalando.logbook: TRACE

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deal
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

feign:
  name: conveyor
  url: http://localhost:8080/conveyor/


exception:
  message:
    application-not-found: "Application wasn't found with id=%s"

log:
  message:
    saved: "{} was saved"

kafka:
  topic:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    application-denied: application-denied

app:
  kafka:
    finish-registration-topic: finish-registration
    create-documents-topic: create-documents
    send-documents-topic: send-documents
    send-ses-topic: send-ses
    credit-issued-topic: credit-issued
    application-denied-topic: application-denied