version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: creditconv-zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: creditconv-kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'finish-registration:1:1,create-documents:1:1,send-documents:1:1,send-ses:1:1,credit-
   issued:1:1,application-denied:1:1'