databaseChangeLog:
  - changeSet:
      id: create-application-table
      author: Zentsova Anastasiia
      changes:
        - createTable:
            tableName: application
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: client_id
                  type: bigint
              - column:
                  name: credit_id
                  type: bigint
              - column:
                  name: status
                  type: varchar(50)
              - column:
                  name: creation_date
                  type: datetime
                  constraints:
                    nullable: false
              - column:
                  name: applied_offer
                  type: jsonb
              - column:
                  name: sign_date
                  type: datetime
              - column:
                  name: ses_code
                  type: varchar(10)
              - column:
                  name: status_history
                  type: jsonb
        - addForeignKeyConstraint:
            baseTableName: application
            baseColumnNames: client_id
            referencedTableName: client
            referencedColumnNames: id
            constraintName: fk_application_client
            onDelete: SET NULL
        - addForeignKeyConstraint:
            baseTableName: application
            baseColumnNames: credit_id
            referencedTableName: credit
            referencedColumnNames: id
            constraintName: fk_application_credit
            onDelete: SET NULL