server:
  port: 8084

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: deal
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: smtp.yandex.ru
    port: 465
    username: loan.conveyor@yandex.ru
    password: zblftlorgpiixtnt
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
#      mail.debug: true

logging:
  level:
    root: INFO
    ru.zentsova.deal: DEBUG
    org.springframework: INFO
    org.zalando.logbook: TRACE

kafka:
  topic:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    application-denied: application-denied

email:
  messages:
    finish-registration-msg: Ваша заявка предварительно одобрена, завершите оформление!
    create-documents-msg: <html><a href="http://localhost:8082/swagger-ui.html/">Сформировать документы</a> POST /deal/document/{applicationId}/send</html>
