server:
  port: 8084
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: deal
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    ru.zentsova.deal: DEBUG
    org.springframework: INFO
    org.zalando.logbook: TRACE

kafka:
  topic:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    application-denied: application-denied